# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lchsk/projects/xstarter

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lchsk/projects/xstarter

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lchsk/projects/xstarter/CMakeFiles /home/lchsk/projects/xstarter/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lchsk/projects/xstarter/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named xstarter

# Build rule for target.
xstarter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xstarter
.PHONY : xstarter

# fast build rule for target.
xstarter/fast:
	$(MAKE) -f CMakeFiles/xstarter.dir/build.make CMakeFiles/xstarter.dir/build
.PHONY : xstarter/fast

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/xstarter.dir/build.make CMakeFiles/xstarter.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/xstarter.dir/build.make CMakeFiles/xstarter.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/xstarter.dir/build.make CMakeFiles/xstarter.dir/src/main.c.s
.PHONY : src/main.c.s

src/scan.o: src/scan.c.o
.PHONY : src/scan.o

# target to build an object file
src/scan.c.o:
	$(MAKE) -f CMakeFiles/xstarter.dir/build.make CMakeFiles/xstarter.dir/src/scan.c.o
.PHONY : src/scan.c.o

src/scan.i: src/scan.c.i
.PHONY : src/scan.i

# target to preprocess a source file
src/scan.c.i:
	$(MAKE) -f CMakeFiles/xstarter.dir/build.make CMakeFiles/xstarter.dir/src/scan.c.i
.PHONY : src/scan.c.i

src/scan.s: src/scan.c.s
.PHONY : src/scan.s

# target to generate assembly for a file
src/scan.c.s:
	$(MAKE) -f CMakeFiles/xstarter.dir/build.make CMakeFiles/xstarter.dir/src/scan.c.s
.PHONY : src/scan.c.s

src/settings.o: src/settings.c.o
.PHONY : src/settings.o

# target to build an object file
src/settings.c.o:
	$(MAKE) -f CMakeFiles/xstarter.dir/build.make CMakeFiles/xstarter.dir/src/settings.c.o
.PHONY : src/settings.c.o

src/settings.i: src/settings.c.i
.PHONY : src/settings.i

# target to preprocess a source file
src/settings.c.i:
	$(MAKE) -f CMakeFiles/xstarter.dir/build.make CMakeFiles/xstarter.dir/src/settings.c.i
.PHONY : src/settings.c.i

src/settings.s: src/settings.c.s
.PHONY : src/settings.s

# target to generate assembly for a file
src/settings.c.s:
	$(MAKE) -f CMakeFiles/xstarter.dir/build.make CMakeFiles/xstarter.dir/src/settings.c.s
.PHONY : src/settings.c.s

src/term.o: src/term.c.o
.PHONY : src/term.o

# target to build an object file
src/term.c.o:
	$(MAKE) -f CMakeFiles/xstarter.dir/build.make CMakeFiles/xstarter.dir/src/term.c.o
.PHONY : src/term.c.o

src/term.i: src/term.c.i
.PHONY : src/term.i

# target to preprocess a source file
src/term.c.i:
	$(MAKE) -f CMakeFiles/xstarter.dir/build.make CMakeFiles/xstarter.dir/src/term.c.i
.PHONY : src/term.c.i

src/term.s: src/term.c.s
.PHONY : src/term.s

# target to generate assembly for a file
src/term.c.s:
	$(MAKE) -f CMakeFiles/xstarter.dir/build.make CMakeFiles/xstarter.dir/src/term.c.s
.PHONY : src/term.c.s

src/utils.o: src/utils.c.o
.PHONY : src/utils.o

# target to build an object file
src/utils.c.o:
	$(MAKE) -f CMakeFiles/xstarter.dir/build.make CMakeFiles/xstarter.dir/src/utils.c.o
.PHONY : src/utils.c.o

src/utils.i: src/utils.c.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.c.i:
	$(MAKE) -f CMakeFiles/xstarter.dir/build.make CMakeFiles/xstarter.dir/src/utils.c.i
.PHONY : src/utils.c.i

src/utils.s: src/utils.c.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.c.s:
	$(MAKE) -f CMakeFiles/xstarter.dir/build.make CMakeFiles/xstarter.dir/src/utils.c.s
.PHONY : src/utils.c.s

src/utils_string.o: src/utils_string.c.o
.PHONY : src/utils_string.o

# target to build an object file
src/utils_string.c.o:
	$(MAKE) -f CMakeFiles/xstarter.dir/build.make CMakeFiles/xstarter.dir/src/utils_string.c.o
.PHONY : src/utils_string.c.o

src/utils_string.i: src/utils_string.c.i
.PHONY : src/utils_string.i

# target to preprocess a source file
src/utils_string.c.i:
	$(MAKE) -f CMakeFiles/xstarter.dir/build.make CMakeFiles/xstarter.dir/src/utils_string.c.i
.PHONY : src/utils_string.c.i

src/utils_string.s: src/utils_string.c.s
.PHONY : src/utils_string.s

# target to generate assembly for a file
src/utils_string.c.s:
	$(MAKE) -f CMakeFiles/xstarter.dir/build.make CMakeFiles/xstarter.dir/src/utils_string.c.s
.PHONY : src/utils_string.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... xstarter"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/scan.o"
	@echo "... src/scan.i"
	@echo "... src/scan.s"
	@echo "... src/settings.o"
	@echo "... src/settings.i"
	@echo "... src/settings.s"
	@echo "... src/term.o"
	@echo "... src/term.i"
	@echo "... src/term.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
	@echo "... src/utils_string.o"
	@echo "... src/utils_string.i"
	@echo "... src/utils_string.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

