# Base URL of the website
url = "https://xstarter.org"

[rss]
# Settings for the RSS feed
generate_rss = true
title = "xstarter - GNU/Linux terminal application launcher"
description = "xstarter.org - terminal application launcher for GNU/Linux"
author_name = "Maciej Lechowski"
author_email = ""